# Logistic Regression

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
clf = LogisticRegression(random_state=0).fit(X, y)

In [33]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [35]:
clf.predict(X_test)

array([1, 0, 2, 1, 2, 1, 1, 0, 1, 0, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 2, 0,
       0, 2, 0, 1, 2, 0, 1, 1])

In [36]:
y_test

array([1, 0, 2, 1, 2, 1, 2, 0, 1, 0, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 2, 0,
       0, 2, 0, 1, 2, 0, 1, 1])

In [9]:
clf.predict_proba(X_test)

array([[2.38735712e-02, 9.59403809e-01, 1.67226193e-02],
       [9.86782288e-01, 1.32176989e-02, 1.27640895e-08],
       [9.56621117e-01, 4.33788146e-02, 6.82548970e-08],
       [9.77375435e-01, 2.26245475e-02, 1.73754790e-08],
       [3.10531600e-08, 4.69416805e-03, 9.95305801e-01],
       [9.84130492e-01, 1.58694876e-02, 2.04924960e-08],
       [1.36321467e-04, 1.56785708e-01, 8.43077970e-01],
       [9.72491303e-01, 2.75085592e-02, 1.37345796e-07],
       [9.64318306e-01, 3.56816239e-02, 7.03464600e-08],
       [2.01467068e-06, 1.26155023e-02, 9.87382483e-01],
       [1.05278976e-06, 2.93191104e-02, 9.70679837e-01],
       [9.09512265e-03, 9.76439276e-01, 1.44656018e-02],
       [9.51861594e-01, 4.81381999e-02, 2.05940436e-07],
       [6.15742666e-07, 2.15387435e-02, 9.78460641e-01],
       [9.78987640e-01, 2.10123503e-02, 9.60448275e-09],
       [9.51610853e-01, 4.83890602e-02, 8.67502034e-08],
       [2.50918568e-02, 9.56447435e-01, 1.84607086e-02],
       [7.04661669e-03, 9.42870

In [38]:
clf.score(X_train, y_train)

0.975

In [39]:
clf.score(X_test, y_test)

0.9666666666666667

# Confusion Matrix

In [3]:
from sklearn.metrics import confusion_matrix

In [11]:
confusion_matrix(y, clf.predict(X))

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  1, 49]], dtype=int64)

In [12]:
confusion_matrix(y, clf.predict(X), normalize='true')

array([[1.  , 0.  , 0.  ],
       [0.  , 0.94, 0.06],
       [0.  , 0.02, 0.98]])

In [ ]:
i

# 1. Solve classification problem using 'classification.csv' dataset

##### target variable is 'default'. Apply feature selection, feature scaling, cross validation etc. (anything you think is needed)

In [4]:
import pandas as pd
df=pd.read_csv('classification.csv')
df.head()

age              ed  employ  address  income  debtinc   creddebt   othdebt  \
0   41  college degree      17       12     176      9.3  11.359392  5.008608   
1   27  no high school      10        6      31     17.3   1.362202  4.000798   
2   40  no high school      15       14      55      5.5   0.856075  2.168925   
3   41  no high school      15       14     120      2.9   2.658720  0.821280   
4   24     high school       2        0      28     17.3   1.787436  3.056564   

   default  
0        1  
1        0  
2        0  
3        0  
4        1

In [5]:
df.ed.unique()

array(['college degree', 'no high school', 'high school', 'undergraduate',
       'postgraduate'], dtype=object)

In [6]:
df.corr()

age    employ   address    income   debtinc  creddebt  \
age       1.000000  0.536497  0.597591  0.478710  0.016398  0.295207   
employ    0.536497  1.000000  0.322334  0.619681 -0.031182  0.403694   
address   0.597591  0.322334  1.000000  0.316245  0.011323  0.208435   
income    0.478710  0.619681  0.316245  1.000000 -0.026777  0.570199   
debtinc   0.016398 -0.031182  0.011323 -0.026777  1.000000  0.501767   
creddebt  0.295207  0.403694  0.208435  0.570199  0.501767  1.000000   
othdebt   0.340217  0.406091  0.226514  0.610659  0.584870  0.633104   
default  -0.137657 -0.282978 -0.164451 -0.070970  0.389575  0.244740   

           othdebt   default  
age       0.340217 -0.137657  
employ    0.406091 -0.282978  
address   0.226514 -0.164451  
income    0.610659 -0.070970  
debtinc   0.584870  0.389575  
creddebt  0.633104  0.244740  
othdebt   1.000000  0.145713  
default   0.145713  1.000000

In [7]:
df = pd.get_dummies(df[['age','ed', 'employ', 'address', 'income', 'debtinc','creddebt','othdebt','default']])

In [8]:
df.head()

age  employ  address  income  debtinc   creddebt   othdebt  default  \
0   41      17       12     176      9.3  11.359392  5.008608        1   
1   27      10        6      31     17.3   1.362202  4.000798        0   
2   40      15       14      55      5.5   0.856075  2.168925        0   
3   41      15       14     120      2.9   2.658720  0.821280        0   
4   24       2        0      28     17.3   1.787436  3.056564        1   

   ed_college degree  ed_high school  ed_no high school  ed_postgraduate  \
0                  1               0                  0                0   
1                  0               0                  1                0   
2                  0               0                  1                0   
3                  0               0                  1                0   
4                  0               1                  0                0   

   ed_undergraduate  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0

In [9]:
y=df.default
df.corr()

age    employ   address    income   debtinc  creddebt  \
age                1.000000  0.536497  0.597591  0.478710  0.016398  0.295207   
employ             0.536497  1.000000  0.322334  0.619681 -0.031182  0.403694   
address            0.597591  0.322334  1.000000  0.316245  0.011323  0.208435   
income             0.478710  0.619681  0.316245  1.000000 -0.026777  0.570199   
debtinc            0.016398 -0.031182  0.011323 -0.026777  1.000000  0.501767   
creddebt           0.295207  0.403694  0.208435  0.570199  0.501767  1.000000   
othdebt            0.340217  0.406091  0.226514  0.610659  0.584870  0.633104   
default           -0.137657 -0.282978 -0.164451 -0.070970  0.389575  0.244740   
ed_college degree  0.051031 -0.029161  0.058899  0.149451  0.032199  0.110548   
ed_high school    -0.059646 -0.073388  0.001322  0.014392 -0.034308 -0.038828   
ed_no high school  0.015432  0.146061 -0.047697 -0.178107  0.005693 -0.056229   
ed_postgraduate    0.082148  0.005245  0.023896  0.163696 -0.042278 -0.009532   
ed_undergraduate  -0.020260 -0.135290  0.007779  0.085204  0.024489  0.043597   

                    othdebt   default  ed_college degree  ed_high school  \
age                0.340217 -0.137657           0.051031       -0.059646   
employ             0.406091 -0.282978          -0.029161       -0.073388   
address            0.226514 -0.164451           0.058899        0.001322   
income             0.610659 -0.070970           0.149451        0.014392   
debtinc            0.584870  0.389575           0.032199       -0.034308   
creddebt           0.633104  0.244740           0.110548       -0.038828   
othdebt            1.000000  0.145713           0.169630       -0.012977   
default            0.145713  1.000000           0.071502        0.052241   
ed_college degree  0.169630  0.071502           1.000000       -0.236597   
ed_high school    -0.012977  0.052241          -0.236597        1.000000   
ed_no high school -0.127588 -0.118909          -0.401203       -0.668829   
ed_postgraduate    0.080032 -0.011857          -0.031954       -0.053269   
ed_undergraduate   0.030057  0.058337          -0.090259       -0.150468   

                   ed_no high school  ed_postgraduate  ed_undergraduate  
age                         0.015432         0.082148         -0.020260  
employ                      0.146061         0.005245         -0.135290  
address                    -0.047697         0.023896          0.007779  
income                     -0.178107         0.163696          0.085204  
debtinc                     0.005693        -0.042278          0.024489  
creddebt                   -0.056229        -0.009532          0.043597  
othdebt                    -0.127588         0.080032          0.030057  
default                    -0.118909        -0.011857          0.058337  
ed_college degree          -0.401203        -0.031954         -0.090259  
ed_high school             -0.668829        -0.053269         -0.150468  
ed_no high school           1.000000        -0.090329         -0.255151  
ed_postgraduate            -0.090329         1.000000         -0.020321  
ed_undergraduate           -0.255151        -0.020321          1.000000

In [10]:
y

0      1
1      0
2      0
3      0
4      1
      ..
695    1
696    0
697    0
698    0
699    0
Name: default, Length: 700, dtype: int64

In [11]:
X_train, X_test, y_train, y_test = train_test_split(df[['age', 'creddebt', 'debtinc', 'ed_college degree', 'ed_high school','ed_no high school', 'ed_postgraduate', 'ed_undergraduate', 'employ','income', 'othdebt']],y, test_size=0.2, random_state=42)

In [12]:
clf = LogisticRegression(random_state=0).fit(X_train, y_train)
y_pre=clf.predict(X_test)
y_pre

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0], dtype=int64)

In [13]:
clf.predict_proba(X_test)

array([[0.84046699, 0.15953301],
       [0.49605961, 0.50394039],
       [0.93773777, 0.06226223],
       [0.76592985, 0.23407015],
       [0.64822658, 0.35177342],
       [0.65185782, 0.34814218],
       [0.97344285, 0.02655715],
       [0.95031988, 0.04968012],
       [0.01210211, 0.98789789],
       [0.31392829, 0.68607171],
       [0.4438297 , 0.5561703 ],
       [0.68019886, 0.31980114],
       [0.27799792, 0.72200208],
       [0.98512838, 0.01487162],
       [0.04214669, 0.95785331],
       [0.47232344, 0.52767656],
       [0.82287463, 0.17712537],
       [0.94623288, 0.05376712],
       [0.7793527 , 0.2206473 ],
       [0.23397705, 0.76602295],
       [0.98132069, 0.01867931],
       [0.12584168, 0.87415832],
       [0.72692413, 0.27307587],
       [0.75096372, 0.24903628],
       [0.85271842, 0.14728158],
       [0.79243836, 0.20756164],
       [0.99784867, 0.00215133],
       [0.68001546, 0.31998454],
       [0.94094783, 0.05905217],
       [0.24827735, 0.75172265],
       [0.

In [14]:
clf.score(X_test, y_test)

0.8571428571428571

In [15]:
clf.score(X_train, y_train)

0.7964285714285714

# 2. Print accuracy, confusion matrix, precision, recall, sensitivity and specifity on train and test (and maybe validation) datasets.

##### do not use any libraries for metrics, implement yourself

### For test data

In [18]:
y1=np.array(y_test)
y1

array([1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0], dtype=int64)

In [17]:
import numpy as np

In [19]:
y_pre

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0], dtype=int64)

In [20]:
true_positive_test = 0
for i in range(len(y1)):
    if y_pre[i]==1 and y1[i]==1:
        true_positive_test +=1

print(true_positive_test)      

22


In [21]:
true_negative_test=0
for i in range(len(y1)):
    if y_pre[i]==0 and y1[i]==0:
        true_negative_test+=1
print(true_negative_test)

98


In [22]:
false_positive_test = 0
for i in range(len(y1)):
    if y_pre[i]==1 and y1[i]==0:
        false_positive_test+=1
        
print(false_positive_test)

4


In [23]:
precision_test = true_positive_test/(true_positive_test + false_positive_test)
precision_test

0.8461538461538461

In [24]:
false_negative_test=0
for i in range(len(y1)):
    if y_pre[i]==0 and y1[i]==1:
        false_negative_test +=1
print(false_negative_test)

16


In [25]:
recall_test = true_positive_test/(true_positive_test + false_negative_test)
recall_test

0.5789473684210527

In [26]:
sensitivity_test= recall_test
sensitivity_test

0.5789473684210527

In [28]:
specifity_test=true_negative_test/(true_negative_test + false_positive_test)
specifity_test

0.9607843137254902

In [29]:
data_test=[[true_positive_test, false_positive_test], [false_negative_test, true_negative_test]]
col = ['Positive', 'Negative']
confusion_matrix_test= pd.DataFrame(data_test, columns = col, index =col)
confusion_matrix_test

Positive  Negative
Positive        22         4
Negative        16        98

In [30]:
from sklearn.metrics import confusion_matrix

In [31]:
confusion_matrix(y1, y_pre)
# սա ինչի ա 98 ու 22ի տեղերը տարբեր?

array([[98,  4],
       [16, 22]], dtype=int64)

In [46]:
accur_test = (true_positive_test+ true_negative_test)/(true_positive_test+ true_negative_test + false_positive_test+false_negative_test)
accur_test

0.8571428571428571

### For train data

In [32]:
y_pre_train=clf.predict(X_train)
y_pre_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [33]:
y2=np.array(y_train)
y2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,

In [34]:
len(y2)

560

In [35]:
true_positive_train = 0
for i in range(len(y2)):
    if y_pre_train[i]==1 and y2[i]==1:
        true_positive_train +=1

print(true_positive_train)      

62


In [36]:
true_negative_train=0
for i in range(len(y2)):
    if y_pre_train[i]==0 and y2[i]==0:
        true_negative_train+=1
print(true_negative_train)

384


In [37]:
false_positive_train = 0
for i in range(len(y2)):
    if y_pre_train[i]==1 and y2[i]==0:
        false_positive_train+=1
        
print(false_positive_train)

31


In [38]:
precision_train = true_positive_train/(true_positive_train + false_positive_train)
precision_train

0.6666666666666666

In [39]:
false_negative_train=0
for i in range(len(y2)):
    if y_pre_train[i]==0 and y2[i]==1:
        false_negative_train +=1
print(false_negative_train)

83


In [40]:
recall_train = true_positive_train/(true_positive_train + false_negative_train)
recall_train

0.42758620689655175

In [41]:
sensitivity_train= recall_train
sensitivity_train

0.42758620689655175

In [42]:
specifity_train=true_negative_train/(true_negative_train + false_positive_train)
specifity_train

0.9253012048192771

In [43]:
data_train=[[true_positive_train, false_positive_train], [false_negative_train, true_negative_train]]
col = ['Positive', 'Negative']
confusion_matrix_train= pd.DataFrame(data_train, columns = col, index =col)
confusion_matrix_train

Positive  Negative
Positive        62        31
Negative        83       384

In [47]:
accur_train = (true_positive_train+ true_negative_train)/(true_positive_train+ true_negative_train + false_positive_train+false_negative_train)
accur_train

0.7964285714285714